name: strapi

type: 'nodejs:18'

build:
    flavor: none

dependencies:
    nodejs: 
        yarn: "*"
variables:
    env:
        NODE_ENV: production
hooks:
    build: |
        yarn --frozen-lockfile
        yarn build

web:
    commands:
        start: .global/bin/yarn start

disk: 1024

mounts:
    'public/uploads':
        source: local
        source_path: uploads
    '/.tmp':
        source: local
        source_path: tmp